# Generated by Django 5.2.12 on 2026-04-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_performancelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccuracyTestCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("question", models.TextField()),
                ("expected_answer", models.TextField(blank=True, help_text="Optional phrase or keyword expected to appear in the chatbot answer.")),
                ("expected_source", models.CharField(blank=True, help_text="Optional source label expected to be cited by the chatbot.", max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AccuracyTestRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_cases", models.IntegerField(default=0)),
                ("passed_cases", models.IntegerField(default=0)),
                ("failed_cases", models.IntegerField(default=0)),
                ("average_latency_ms", models.FloatField(default=0)),
                ("status", models.CharField(default="completed", max_length=20)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AccuracyTestResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chatbot_answer", models.TextField(blank=True)),
                ("returned_sources", models.TextField(blank=True)),
                ("answer_match", models.BooleanField(default=False)),
                ("source_match", models.BooleanField(default=False)),
                ("passed", models.BooleanField(default=False)),
                ("latency_ms", models.FloatField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("run", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="results", to="core.accuracytestrun")),
                ("test_case", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="results", to="core.accuracytestcase")),
            ],
            options={
                "ordering": ["test_case__name", "-created_at"],
            },
        ),
    ]
